apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  type: ClusterIP
  ports:
    - name: scrape
      port: 9100
      protocol: TCP
  selector:
    app: node-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      serviceAccountName: service-account
      containers:
        - image: prom/node-exporter:v1.0.1
          name: node-exporter
          ports:
            - containerPort: 9100
              hostPort: 9100
              name: scrape
      hostNetwork: true
      hostPID: true
