apiVersion: v1
kind: Service
metadata:
  name: innkeeper-ui-cluster-ip-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: innkeeper-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innkeeper-ui-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
          component: innkeeper-ui
  template:
      metadata:
          labels:
              component: innkeeper-ui
      spec:
          containers:
              - name: innkeeper
                image: jordan396/innkeeper-ui
                ports:
                  - containerPort: 8080
                env:
                  - name: INNKEEPER_UI_CLUSTER_IP_SERVICE
                    value: $(INNKEEPER_UI_CLUSTER_IP_SERVICE)
                command: ["./app"]
                args: ["start"]