apiVersion: v1
kind: ServiceAccount
metadata:
  name: service-account
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: RBAC
subjects:
  - kind: ServiceAccount
    name: service-account
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
