apiVersion: v1
kind: Service
metadata:
  name: postgrest-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: postgrest
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgrest
  template:
    metadata:
      labels:
        component: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest
          ports:
            - containerPort: 3000
          volumeMounts:
          - name: postgrest-conf
            mountPath: "/etc"
      initContainers:
      - name: set-db-uri
        image: busybox
        command:
        - echo "db-uri       = \"postgres://$(PGUSER):$(PGPASSWORD)@$(PGHOST):$(PGPORT)/$(PGDATABASE)\"" >> postgrest.conf
        env:
          - name: PGHOST
            value: $(POSTGRES_CLUSTER_IP_SERVICE)
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: postgres-conf
                key: PGUSER
          - name: PGPORT
            valueFrom:
              configMapKeyRef:
                name: postgres-conf
                key: PGPORT
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: postgres-conf
                key: PGDATABASE
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: pgpassword
                key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgrest-conf
          mountPath: "/etc"
      volumes: 
      - name : postgrest-conf
        configMap:
          name: postgrest-conf