apiVersion: v1
kind: Service
metadata:
  name: schutterij-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: schutterij
  ports:
    - port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schutterij-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: schutterij
  template:
    metadata:
      labels:
        component: schutterij
    spec:
      containers:
        - name: schutterij
          image: jordan396/schutterij
          ports:
            - containerPort: 5000
          env:
            - name: PGHOST
              value: $(POSTGRES_CLUSTER_IP_SERVICE)
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGUSER
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGDATABASE
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
          command: ["/app/main"]
          args: ["--kubecfg", "/app/configs/.kube/config"]
