# Schutterij is exposed on a NodePort
apiVersion: v1
kind: Service
metadata:
  name: schutterij-node-port-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    component: schutterij
---
apiVersion: v1
kind: Service
metadata:
  name: schutterij-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: schutterij
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: schutterij-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: schutterij
  template:
    metadata:
      labels:
        component: schutterij
    spec:
      serviceAccountName: service-account
      containers:
        - name: schutterij
          image: jordan396/schutterij
          ports:
            - containerPort: 8080
          env:
            - name: PGHOST
              value: $(POSTGRES_CLUSTER_IP_SERVICE)
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGUSER
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGPORT
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: PGDATABASE
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: POSTGRES_PASSWORD
            - name: JWT_SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-signing-key
                  key: JWT_SIGNING_KEY
          command: ["/app/main"]
          args: ["--kubecfg", "/app/configs/.kube/config"]
