# # NodePort is for debugging purposes
# apiVersion: v1
# kind: Service
# metadata:
#   name: innkeeper-node-port-service
# spec:
#   type: NodePort
#   ports:
#     - port: 80
#       targetPort: 80
#       nodePort: 30002
#   selector:
#     component: innkeeper
---
apiVersion: v1
kind: Service
metadata:
  name: innkeeper-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: innkeeper
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: innkeeper-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: innkeeper
  template:
    metadata:
      labels:
        component: innkeeper
    spec:
      serviceAccountName: service-account
      containers:
        - name: innkeeper
          image: jordan396/innkeeper
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name: tmp-files
              mountPath: "/usr/share/nginx/html/innkeeper/config"
      initContainers:
        - name: create-env-config
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            [
              "cp /configmap/.env /tmp/files/ && cp /configmap/env.sh /tmp/files/ && cd /tmp/files/ && /bin/sh ./env.sh",
            ]
          volumeMounts:
            - name: react-env-volume
              mountPath: "/configmap"
              readOnly: true
            - name: tmp-files
              mountPath: "/tmp/files"
      volumes:
        - name: react-env-volume
          configMap:
            name: react-env-conf
        - name: tmp-files
          emptyDir: {}
