apiVersion: v1
kind: Service
metadata:
  name: crossroads-cluster-ip-service
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: crossroads
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crossroads-deployment
spec:
  replicas: 1
  selector:
      matchLabels:
          component: crossroads
  template:
      metadata:
          labels:
              component: crossroads
      spec:
          containers:
              - name: crossroads
                image: jordan396/crossroads
                ports:
                  - containerPort: 8080